#ifndef CONTROL_SYSTEM_VERSION_H
#define CONTROL_SYSTEM_VERSION_H

#define CONTROL_SYSTEM_VERSION_MAJOR 1
#define CONTROL_SYSTEM_VERSION_MINOR 0
#define CONTROL_SYSTEM_VERSION_PATCH 0

#define CONTROL_SYSTEM_VERSION (CONTROL_SYSTEM_VERSION_MAJOR * 10000 + CONTROL_SYSTEM_VERSION_MINOR * 100 + CONTROL_SYSTEM_VERSION_PATCH)

#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)

#define CONTROL_SYSTEM_VERSION_STRING STRINGIFY(CONTROL_SYSTEM_VERSION_MAJOR) "." STRINGIFY(CONTROL_SYSTEM_VERSION_MINOR) "." STRINGIFY(CONTROL_SYSTEM_VERSION_PATCH)

namespace CONTROL_SYSTEM
{
    inline constexpr int version_major = CONTROL_SYSTEM_VERSION_MAJOR;
    inline constexpr int version_minor = CONTROL_SYSTEM_VERSION_MINOR;
    inline constexpr int version_patch = CONTROL_SYSTEM_VERSION_PATCH;
    inline constexpr int version = CONTROL_SYSTEM_VERSION;
    inline constexpr const char *version_string = CONTROL_SYSTEM_VERSION_STRING;
}

#endif
